# -*- coding: utf-8 -*-

# Prefix of default document collection of this instance
FST_INSTANCE_PREFIX = "exfs"

# Organization authorized to publish these documents.
FST_ORG_NAME = "Exempelmyndigheten"
FST_ORG_NAME_POSSESSIVE = "Exempelmyndighetens"

# Contact information for ATOM feed
FST_ORG_CONTACT_NAME = "Johan Exempelson"
FST_ORG_CONTACT_URL = "http://www.exfs.se/"
FST_ORG_CONTACT_EMAIL = "lagrum@eempelmyndigheten.se"

# Description of data source for Atom feed.
# Feeds generated by FST should end with 2016:fst:feed.
# Make sure the tag value is unique for your organization
FST_DATASET_URI = "tag:exfs.se,2016:fst:feed"
FST_DATASET_TITLE = "Flöde för Exempelmyndighetens författningssamling"