# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 07:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fst_web.fs_doc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amnesord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text=b'\xc3\x84mnesordet', max_length=255, unique=True)),
                ('beskrivning', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '\xe4mnesord',
                'verbose_name_plural': '\xc4mnesord',
            },
        ),
        migrations.CreateModel(
            name='Andringar_fsdokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AtomEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name=b'object_id')),
                ('entry_id', models.CharField(max_length=512)),
                ('updated', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            bases=(models.Model, fst_web.fs_doc.models.GenericUniqueMixin),
        ),
        migrations.CreateModel(
            name='Bemyndigandereferens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text=b'T.ex. <em>Arkivf\xc3\xb6rordningen</em>', max_length=255)),
                ('sfsnummer', models.CharField(help_text=b'T.ex. <em>1991:446</em>', max_length=10, verbose_name=b'SFS-nummer')),
                ('kapitelnummer', models.CharField(blank=True, help_text=b'T.ex. <em>12</em>', max_length=10)),
                ('paragrafnummer', models.CharField(blank=True, help_text=b'T.ex. <em>12</em>', max_length=10)),
                ('kommentar', models.CharField(blank=True, help_text=b'T.ex. <em>r\xc3\xa4tt att meddela f\xc3\xb6reskrifter om                                 notarietj\xc3\xa4nstg\xc3\xb6ring och                                  notariemeritering</em>', max_length=255)),
            ],
            options={
                'verbose_name': 'bemyndigandereferens',
                'verbose_name_plural': 'Bemyndigandereferenser',
            },
        ),
        migrations.CreateModel(
            name='Bilaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_md5', models.CharField(blank=True, max_length=32)),
                ('titel', models.CharField(blank=True, help_text=b'T.ex. <em>Bilaga 1</em>', max_length=512, verbose_name=b'Titel')),
                ('file', models.FileField(blank=True, help_text=b'Om ingen fil anges f\xc3\xb6ruts\xc3\xa4tts bilagan                             vara en del av f\xc3\xb6reskriftsdokumentet.', storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to=b'bilaga', verbose_name='Fil')),
            ],
            options={
                'verbose_name': 'bilaga',
                'verbose_name_plural': 'Bilagor',
            },
        ),
        migrations.CreateModel(
            name='CelexReferens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField(blank=True, help_text=b'Titel')),
                ('celexnummer', models.CharField(help_text=b'Celexnummer, t.ex. <em>31979L0409</em>', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'EG-r\xe4ttsreferens',
                'verbose_name_plural': 'EG-r\xe4ttsreferenser',
            },
        ),
        migrations.CreateModel(
            name='Forfattningssamling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text=b'Fullst\xc3\xa4ndigt namn, t.ex.\n            <em>Exempelmyndighetens f\xc3\xb6rfattningssamling</em>', max_length=255, unique=True)),
                ('kortnamn', models.CharField(help_text=b'T.ex. <em>EXFS</em>', max_length=10, unique=True)),
                ('slug', models.CharField(help_text=b'T.ex. <em>exfs</em>', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'f\xf6rfattningssamling',
                'verbose_name_plural': 'F\xf6rfattningssamlingar',
            },
        ),
        migrations.CreateModel(
            name='FSDokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arsutgava', models.CharField(default=2016, max_length=13, validators=[django.core.validators.RegexValidator(message='Ange \xe5r som 19YY eller 20YY', regex=b'^(19|20)\\d\\d')], verbose_name=b'\xc3\x85rsutg\xc3\xa5va')),
                ('lopnummer', models.CharField(default=fst_web.fs_doc.models.next_lopnummer, max_length=3, validators=[django.core.validators.RegexValidator(message='L\xf6pnummer f\xe5r bara inneh\xe5lla siffror', regex=b'^\\d+$')], verbose_name=b'L\xc3\xb6pnummer')),
                ('is_published', models.BooleanField(default=False, help_text=b'Gr\xc3\xb6n bock = publicerad.                                        R\xc3\xb6tt streck = ej publicerad.                                        Gl\xc3\xb6m inte att publicera dina \xc3\xa4ndringar!\n                                     ', verbose_name='Publicerad via FST')),
                ('titel', models.CharField(max_length=512)),
                ('sammanfattning', models.TextField(blank=True, help_text=b'<em>Valfri sammanfattning av dokuments syfte.</em>', max_length=8192)),
                ('beslutsdatum', models.DateField(verbose_name=b'Beslutsdatum')),
                ('ikrafttradandedatum', models.DateField(verbose_name=b'Ikrafttr\xc3\xa4dandedatum')),
                ('utkom_fran_tryck', models.DateField(verbose_name=b'Utkom fr\xc3\xa5n tryck')),
                ('omtryck', models.BooleanField(default=False, verbose_name='\xc4r omtryck')),
                ('content_md5', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KonsolideradForeskrift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=512, unique=True)),
                ('konsolideringsdatum', models.DateField(verbose_name=b'Konsolideringsdatum')),
                ('content', models.FileField(help_text=b'Se till att dokumentet \xc3\xa4r i PDF-format.', upload_to=b'konsoliderad_foreskrift', verbose_name='PDF-version')),
                ('content_md5', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': 'konsoliderad f\xf6reskrift',
                'verbose_name_plural': 'Konsoliderade f\xf6reskrifter',
            },
        ),
        migrations.CreateModel(
            name='Konsolideringar_foreskrift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Myndighet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(help_text=b'Myndighetens fullst\xc3\xa4ndiga namn', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'myndighet',
                'verbose_name_plural': 'Myndigheter',
            },
        ),
        migrations.CreateModel(
            name='OvrigtDokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_md5', models.CharField(blank=True, max_length=32)),
                ('titel', models.CharField(help_text=b'T.ex. <em>Besluts-PM f\xc3\xb6r ...</em>', max_length=512, verbose_name=b'Titel')),
                ('file', models.FileField(storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to=b'ovrigt', verbose_name='Fil')),
            ],
            options={
                'verbose_name': '\xf6vrigt dokument',
                'verbose_name_plural': '\xd6vriga dokument',
            },
        ),
        migrations.CreateModel(
            name='RDFPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name=b'object_id')),
                ('slug', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('md5', models.CharField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            bases=(models.Model, fst_web.fs_doc.models.GenericUniqueMixin),
        ),
        migrations.CreateModel(
            name='Upphavningar_fsdokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AllmannaRad',
            fields=[
                ('fsdokument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fs_doc.FSDokument')),
                ('content', models.FileField(help_text=b'Se till att dokumentet \xc3\xa4r i PDF-format.', storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to=b'allmanna_rad', verbose_name='PDF-version')),
                ('andringar', models.ManyToManyField(blank=True, related_name='andringar_allmannarad', to='fs_doc.AllmannaRad', verbose_name='Dokument som \xe4ndras')),
                ('beslutad_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_beslutad_av', to='fs_doc.Myndighet')),
                ('konsolideringar', models.ManyToManyField(blank=True, related_name='konsolideringar_allmannarad', to='fs_doc.AllmannaRad', verbose_name='Konsolideringsunderlag')),
                ('upphavningar', models.ManyToManyField(blank=True, related_name='upphavningar_allmannarad', to='fs_doc.AllmannaRad', verbose_name='Dokument som upph\xe4vs')),
                ('utgivare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_utgivare', to='fs_doc.Myndighet')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'allm\xe4nna r\xe5d',
                'verbose_name_plural': 'Allm\xe4nna r\xe5d',
            },
            bases=('fs_doc.fsdokument',),
        ),
        migrations.CreateModel(
            name='Myndighetsforeskrift',
            fields=[
                ('fsdokument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fs_doc.FSDokument')),
                ('content', models.FileField(help_text=b'Se till att dokumentet \xc3\xa4r i PDF-format.', storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to=b'foreskrift', verbose_name='PDF-version')),
                ('andringar', models.ManyToManyField(blank=True, related_name='andringar_foreskrift', to='fs_doc.Myndighetsforeskrift', verbose_name='Dokument som \xe4ndras')),
                ('bemyndiganden', models.ManyToManyField(to='fs_doc.Bemyndigandereferens', verbose_name='referenser till bemyndiganden')),
                ('beslutad_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_beslutad_av', to='fs_doc.Myndighet')),
                ('celexreferenser', models.ManyToManyField(blank=True, related_name='foreskrifter', to='fs_doc.CelexReferens', verbose_name='Bidrar till att genomf\xf6ra                                              dessa EG-direktiv')),
                ('konsolideringar', models.ManyToManyField(blank=True, related_name='konsolideringar_foreskrift', to='fs_doc.Myndighetsforeskrift', verbose_name='Konsolideringsunderlag')),
                ('upphavningar', models.ManyToManyField(blank=True, related_name='upphavningar_foreskrift', to='fs_doc.Myndighetsforeskrift', verbose_name='Dokument som upph\xe4vs')),
                ('utgivare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_utgivare', to='fs_doc.Myndighet')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'myndighetsf\xf6reskrift',
                'verbose_name_plural': 'Myndighetsf\xf6reskrifter',
            },
            bases=('fs_doc.fsdokument',),
        ),
        migrations.AddField(
            model_name='upphavningar_fsdokument',
            name='from_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelling', to='fs_doc.FSDokument'),
        ),
        migrations.AddField(
            model_name='upphavningar_fsdokument',
            name='to_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled', to='fs_doc.FSDokument'),
        ),
        migrations.AddField(
            model_name='ovrigtdokument',
            name='foreskrift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovriga_dokument', to='fs_doc.FSDokument'),
        ),
        migrations.AddField(
            model_name='fsdokument',
            name='amnesord',
            field=models.ManyToManyField(blank=True, to='fs_doc.Amnesord', verbose_name='\xe4mnesord'),
        ),
        migrations.AddField(
            model_name='fsdokument',
            name='forfattningssamling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs_doc.Forfattningssamling', verbose_name='f\xf6rfattningssamling'),
        ),
        migrations.AddField(
            model_name='bilaga',
            name='foreskrift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilagor', to='fs_doc.FSDokument'),
        ),
        migrations.AddField(
            model_name='atomentry',
            name='rdf_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fs_doc.RDFPost'),
        ),
        migrations.AddField(
            model_name='andringar_fsdokument',
            name='from_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changing', to='fs_doc.FSDokument'),
        ),
        migrations.AddField(
            model_name='andringar_fsdokument',
            name='to_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed', to='fs_doc.FSDokument'),
        ),
        migrations.AlterUniqueTogether(
            name='rdfpost',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AddField(
            model_name='konsolideringar_foreskrift',
            name='from_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidating', to='fs_doc.Myndighetsforeskrift'),
        ),
        migrations.AddField(
            model_name='konsolideringar_foreskrift',
            name='to_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated', to='fs_doc.Myndighetsforeskrift'),
        ),
        migrations.AddField(
            model_name='konsolideradforeskrift',
            name='grundforfattning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grundforfattning', to='fs_doc.Myndighetsforeskrift'),
        ),
        migrations.AddField(
            model_name='konsolideradforeskrift',
            name='senaste_andringsforfattning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senaste_andringsforfattning', to='fs_doc.Myndighetsforeskrift'),
        ),
    ]
