# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 08:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import fst_web.fs_doc.models


class Migration(migrations.Migration):

    dependencies = [
        ('fs_doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmannarad',
            name='content',
            field=models.FileField(help_text='Se till att dokumentet är i PDF-format.', storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to='allmanna_rad', verbose_name='PDF-version'),
        ),
        migrations.AlterField(
            model_name='amnesord',
            name='titel',
            field=models.CharField(help_text='Ämnesordet', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='atomentry',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='object_id'),
        ),
        migrations.AlterField(
            model_name='bemyndigandereferens',
            name='kapitelnummer',
            field=models.CharField(blank=True, help_text='T.ex. <em>12</em>', max_length=10),
        ),
        migrations.AlterField(
            model_name='bemyndigandereferens',
            name='kommentar',
            field=models.CharField(blank=True, help_text='T.ex. <em>rätt att meddela föreskrifter om                                 notarietjänstgöring och                                  notariemeritering</em>', max_length=255),
        ),
        migrations.AlterField(
            model_name='bemyndigandereferens',
            name='paragrafnummer',
            field=models.CharField(blank=True, help_text='T.ex. <em>12</em>', max_length=10),
        ),
        migrations.AlterField(
            model_name='bemyndigandereferens',
            name='sfsnummer',
            field=models.CharField(help_text='T.ex. <em>1991:446</em>', max_length=10, verbose_name='SFS-nummer'),
        ),
        migrations.AlterField(
            model_name='bemyndigandereferens',
            name='titel',
            field=models.CharField(help_text='T.ex. <em>Arkivförordningen</em>', max_length=255),
        ),
        migrations.AlterField(
            model_name='bilaga',
            name='file',
            field=models.FileField(blank=True, help_text='Om ingen fil anges förutsätts bilagan                             vara en del av föreskriftsdokumentet.', storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to='bilaga', verbose_name='Fil'),
        ),
        migrations.AlterField(
            model_name='bilaga',
            name='titel',
            field=models.CharField(blank=True, help_text='T.ex. <em>Bilaga 1</em>', max_length=512, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='celexreferens',
            name='celexnummer',
            field=models.CharField(help_text='Celexnummer, t.ex. <em>31979L0409</em>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='celexreferens',
            name='titel',
            field=models.TextField(blank=True, help_text='Titel'),
        ),
        migrations.AlterField(
            model_name='forfattningssamling',
            name='kortnamn',
            field=models.CharField(help_text='T.ex. <em>EXFS</em>', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='forfattningssamling',
            name='slug',
            field=models.CharField(help_text='T.ex. <em>exfs</em>', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='forfattningssamling',
            name='titel',
            field=models.CharField(help_text='Fullständigt namn, t.ex.\n            <em>Exempelmyndighetens författningssamling</em>', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fsdokument',
            name='arsutgava',
            field=models.CharField(default=2016, max_length=13, validators=[django.core.validators.RegexValidator(message='Ange år som 19YY eller 20YY', regex='^(19|20)\\d\\d')], verbose_name='Årsutgåva'),
        ),
        migrations.AlterField(
            model_name='fsdokument',
            name='beslutsdatum',
            field=models.DateField(verbose_name='Beslutsdatum'),
        ),
        migrations.AlterField(
            model_name='fsdokument',
            name='ikrafttradandedatum',
            field=models.DateField(verbose_name='Ikraftträdandedatum'),
        ),
        migrations.AlterField(
            model_name='fsdokument',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Grön bock = publicerad.                                        Rött streck = ej publicerad.                                        Glöm inte att publicera dina ändringar!\n                                     ', verbose_name='Publicerad via FST'),
        ),
        migrations.AlterField(
            model_name='fsdokument',
            name='lopnummer',
            field=models.CharField(default=fst_web.fs_doc.models.next_lopnummer, max_length=3, validators=[django.core.validators.RegexValidator(message='Löpnummer får bara innehålla siffror', regex='^\\d+$')], verbose_name='Löpnummer'),
        ),
        migrations.AlterField(
            model_name='fsdokument',
            name='sammanfattning',
            field=models.TextField(blank=True, help_text='<em>Valfri sammanfattning av dokuments syfte.</em>', max_length=8192),
        ),
        migrations.AlterField(
            model_name='fsdokument',
            name='utkom_fran_tryck',
            field=models.DateField(verbose_name='Utkom från tryck'),
        ),
        migrations.AlterField(
            model_name='konsolideradforeskrift',
            name='content',
            field=models.FileField(help_text='Se till att dokumentet är i PDF-format.', upload_to='konsoliderad_foreskrift', verbose_name='PDF-version'),
        ),
        migrations.AlterField(
            model_name='konsolideradforeskrift',
            name='konsolideringsdatum',
            field=models.DateField(verbose_name='Konsolideringsdatum'),
        ),
        migrations.AlterField(
            model_name='myndighet',
            name='namn',
            field=models.CharField(help_text='Myndighetens fullständiga namn', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myndighetsforeskrift',
            name='content',
            field=models.FileField(help_text='Se till att dokumentet är i PDF-format.', storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to='foreskrift', verbose_name='PDF-version'),
        ),
        migrations.AlterField(
            model_name='ovrigtdokument',
            name='file',
            field=models.FileField(storage=fst_web.fs_doc.models.OverwritingStorage(), upload_to='ovrigt', verbose_name='Fil'),
        ),
        migrations.AlterField(
            model_name='ovrigtdokument',
            name='titel',
            field=models.CharField(help_text='T.ex. <em>Besluts-PM för ...</em>', max_length=512, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='rdfpost',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='object_id'),
        ),
    ]
